# Generated by Django 3.0.5 on 2020-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200819_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/profile/'),
        ),
    ]
