# Generated by Django 3.0.5 on 2020-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200819_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
